export const PRODUCT_CATEGORIES = [
  "Accesorios",
  "Teclados",
  "Ratones",
  "Gaming",
  "Monitores",
  "Audio",
  "Adaptadores",
  "Wearables",
  "Dispositivos Inteligentes",
  "Almacenamiento",
  "Muebles",
  "Oficina",
  "Hogar",
  "Portátiles",
  "Teléfonos",
  "Cargadores",
  "VR",
];
